---
development:
  dialect: mysql
  database: movie_suggestor
  user: root
  password: root@12345
  host: 127.0.0.1
  pool: 5

test:
  dialect: mysql
  database: movie_suggestor
  user: admin
  password: admin@12345
  host: 127.0.0.1
  pool: 5

production:
  dialect: mysql
  database: movie_suggestor
  user: admin
  password: admin@12345
  host: 127.0.0.1
  pool: 5
